### ISSUE TITLE
Simple example for parsing X.509 certificate

### ISSUE THREAD

**Issue by carlskii** [PeculiarVentures/PKI.js#57]
Hi, 

Is there a simple nodejs example for parsing an X.509 certificate in PEM format? I read through and tried to use some of the examples but didn't get very far. 

Thanks

**Comment by rmhrisk** [comment]
Have you looked at: https://pkijs.org/examples/X509_cert_complex_example.html

**Comment by carlskii** [comment]
Thanks, this was usefull and so adapted this to use nodejs:

https://github.com/GlobalSign/PKI.js/blob/master/examples/certificate-decode-example.html

However, I keep getting `Error: Object's schema was not verified against input data for CERT` whenever it tries to load the ASN1 data. This works OK in the browser though. 

Anything I could be missing here ? 

```
Error: Object's schema was not verified against input data for CERT
    at in_window.org.pkijs.simpl.CERT.fromSchema (/Users/Development/electron/electron-remote/app/node_modules/pkijs/org/pkijs/x509_simpl.js:3912:19)
    at new in_window.org.pkijs.simpl.CERT (/Users/Development/electron/electron-remote/app/node_modules/pkijs/org/pkijs/x509_simpl.js:3854:65)
    at getCertificateData (/Users/Development/electron/electron-remote/app/parse_cert_2.js:107:24)
    at Object.<anonymous> (/Users/Development/electron/electron-remote/app/parse_cert_2.js:214:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
```

```javascript

var merge = require("node.extend");

var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");

// #region Merging function/object declarations for ASN1js and PKIjs
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs = merge(true, pkijs_1, x509schema);

certb = `-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkG
A1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jv
b3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw05ODA5MDExMjAw
MDBaFw0yODAxMjgxMjAwMDBaMFcxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9i
YWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYDVQQDExJHbG9iYWxT
aWduIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaDuaZ
jc6j40+Kfvvxi4Mla+pIH/EqsLmVEQS98GPR4mdmzxzdzxtIK+6NiY6arymAZavp
xy0Sy6scTHAHoT0KMM0VjU/43dSMUBUc71DuxC73/OlS8pF94G3VNTCOXkNz8kHp
1Wrjsok6Vjk4bwY8iGlbKk3Fp1S4bInMm/k8yuX9ifUSPJJ4ltbcdG6TRGHRjcdG
snUOhugZitVtbNV4FpWi6cgKOOvyJBNPc1STE4U6G7weNLWLBYy5d4ux2x8gkasJ
U26Qzns3dLlwR5EiUWMWea6xrkEmCMgZK9FGqkjWZCrXgzT/LCrBbBlDSgeF59N8
9iFo7+ryUp9/k5DPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E
BTADAQH/MB0GA1UdDgQWBBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0B
AQUFAAOCAQEA1nPnfE920I2/7LqivjTFKDK1fPxsnCwrvQmeU79rXqoRSLblCKOz
yj1hTdNGCbM+w6DjY1Ub8rrvrTnhQ7k4o+YviiY776BQVvnGCv04zcQLcFGUl5gE
38NflNUVyRRBnMRddWQVDf9VMOyGj/8N7yy5Y0b2qvzfvGn9LhJIZJrglfCm7ymP
AbEVtQwdpf5pLGkkeB6zpxxxYu7KyJesF12KwvhHhm4qxFYxldBniYUr+WymXUad
DKqC5JlR3XC321Y9YeRq4VzW9v493kHMB65jUr9TU/Qr6cf9tveCX4XSQRjbgbME
HMUfpIBvFSDJ3gyICh3WZlXi/EjJKSZp4A==
-----END CERTIFICATE-----`

//console.log(certb)


    function getCertificateData()
    {
        // function to convert certificate serial from buffer array if needed
        function toHexCodes(input_buffer)
        {
            var result = "";
            var int_buffer = new Uint8Array(input_buffer);

            for(var i = 0; i < int_buffer.length; i++)
            {
                var str = int_buffer[i].toString(16).toUpperCase();
                result = result + ((str.length === 1) ? " 0" : " ") + str;
            }
            return result;
        };

        // function to convert string to ArrayBuffer
        function str2ab(str)
        {
            var buf = new ArrayBuffer(str.length);
            var bufView = new Uint8Array(buf);

            for(var i = 0, strLen = str.length; i < strLen; i++)
                bufView[i] = str.charCodeAt(i);

            return buf;
        };

        // strip certificate header/footer from PEM
       //     var CertPEM = document.getElementById("pem-text-block").value.replace(/(-----(BEGIN|END) CERTIFICATE-----|\n)/g, ''),


            var CertPEM = certb.replace(/(-----(BEGIN|END) CERTIFICATE-----|\n)/g, ''),

        CertBuf = str2ab(CertPEM),     // convert stripped PEM to ArrayBuffer
            algomap = {
                "1.2.840.113549.2.1": "MD2",
                "1.2.840.113549.1.1.2": "MD2 with RSA",
                "1.2.840.113549.2.5": "MD5",
                "1.2.840.113549.1.1.4": "MD5 with RSA",
                "1.3.14.3.2.26": "SHA1",
                "1.2.840.10040.4.3": "SHA1 with DSA",
                "1.2.840.10045.4.1": "SHA1 with ECDSA",
                "1.2.840.113549.1.1.5": "SHA1 with RSA",
                "2.16.840.1.101.3.4.2.4": "SHA224",
                "1.2.840.113549.1.1.14": "SHA224 with RSA",
                "2.16.840.1.101.3.4.2.1": "SHA256",
                "1.2.840.113549.1.1.11": "SHA256 with RSA",
                "2.16.840.1.101.3.4.2.2": "SHA384",
                "1.2.840.113549.1.1.12": "SHA384 with RSA",
                "2.16.840.1.101.3.4.2.3": "SHA512",
                "1.2.840.113549.1.1.13": "SHA512 with RSA"
            };       // array mapping of common algorithm OIDs and corresponding types


        // calls to convert b64 PEM cert to an array in the variable 'cert_simpl'
      var asn1 = pkijs.org.pkijs.fromBER(CertBuf);
      var cert_simpl = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result });



        // checks if serial is hex or not, converts value if it is hex
        if(cert_simpl.serialNumber.value_block.is_hex_only == true)
            //document.getElementById("serial").innerHTML = toHexCodes(cert_simpl.serialNumber.value_block.value_hex);
            console.log(toHexCodes(cert_simpl.serialNumber.value_block.value_hex))
        else
            //document.getElementById("serial").innerHTML = cert_simpl.serialNumber.value_block.value_dec;
        console.log(cert_simpl.serialNumber.value_block.value_dec)

        //document.getElementById("cert-subject").innerHTML = "";

        // loop to get the subject key and values
        for(var i = 0; i < cert_simpl.subject.types_and_values.length; i++)
        {
            // OID map
            var typemap = {
                    "2.5.4.6": "C",
                    "2.5.4.10": "OU",
                    "2.5.4.11": "O",
                    "2.5.4.3": "CN",
                    "2.5.4.7": "L",
                    "2.5.4.8": "S",
                    "2.5.4.12": "T",
                    "2.5.4.42": "GN",
                    "2.5.4.43": "I",
                    "2.5.4.4": "SN"
                },
                typeval = typemap[cert_simpl.subject.types_and_values[i].type],
                subjval = cert_simpl.subject.types_and_values[i].value.value_block.value,
                ulrow = "<li><p><span>"+typeval+"</span> "+subjval+"</p></li>";

         //   document.getElementById("cert-subject").innerHTML = document.getElementById("cert-subject").innerHTML + ulrow;
            console.log(ulrow)
            if(typeval == "CN")
         //       document.getElementById("cert-subject-cn").innerHTML = subjval;
            console.log(subjval)
        };

 //       document.getElementById("cert-exten").innerHTML = "";

        // loop to get extensions
        for(var i = 0; i < cert_simpl.extensions.length; i++)
        {
            // OID map
            var extenmap = {
                    "2.5.29.1": "old Authority Key Identifier",
                    "2.5.29.2": "old Primary Key Attributes",
                    "2.5.29.3": "Certificate Policies",
                    "2.5.29.4": "Primary Key Usage Restriction",
                    "2.5.29.9": "Subject Directory Attributes",
                    "2.5.29.14": "Subject Key Identifier",
                    "2.5.29.15": "Key Usage",
                    "2.5.29.16": "Private Key Usage Period",
                    "2.5.29.17": "Subject Alternative Name",
                    "2.5.29.18": "Issuer Alternative Name",
                    "2.5.29.19": "Basic Constraints",
                    "2.5.29.28": "Issuing Distribution Point",
                    "2.5.29.29": "Certificate Issuer",
                    "2.5.29.30": "Name Constraints",
                    "2.5.29.31": "CRL Distribution Points",
                    "2.5.29.32": "Certificate Policies",
                    "2.5.29.33": "Policy Mappings",
                    "2.5.29.35": "Authority Key Identifier",
                    "2.5.29.36": "Policy Constraints",
                    "2.5.29.37": "Extended key usage",
                    "2.5.29.54": "X.509 version 3 certificate extension Inhibit Any-policy"
                },
                extenval = extenmap[cert_simpl.extensions[i].extnID],
                extenrow = "<li><p>"+extenval+"</p></li>";

       //     document.getElementById("cert-exten").innerHTML = document.getElementById("cert-exten").innerHTML + extenrow;
            console.log(extenrow)
        };

        var asn1_publicKey = org.pkijs.fromBER(cert_simpl.subjectPublicKeyInfo.subjectPublicKey.value_block.value_hex),
            rsa_publicKey_simple = new org.pkijs.simpl.x509.RSAPublicKey({ schema: asn1_publicKey.result }),
            modulus_view = new Uint8Array(rsa_publicKey_simple.modulus.value_block.value_hex),
            modulus_bit_length = 0;

        if(modulus_view[0] === 0x00)
            modulus_bit_length = (rsa_publicKey_simple.modulus.value_block.value_hex.byteLength - 1) * 8;
        else
            modulus_bit_length = rsa_publicKey_simple.modulus.value_block.value_hex.byteLength * 8;

        var publicExponent_bit_length = rsa_publicKey_simple.publicExponent.value_block.value_hex.byteLength * 8;

        console.log(publicExponent_bit_length)

     //   document.getElementById("keysize").innerHTML = modulus_bit_length;
        console.log(modulus_bit_length)

        // get issuance date
     //   document.getElementById("issued").innerHTML = cert_simpl.notBefore.value.toUTCString();
        console.log(cert_simpl.notBefore.value.toUTCString())

        // get expiration date
      //  document.getElementById("expire").innerHTML = cert_simpl.notAfter.value.toUTCString();
        console.log(cert_simpl.notAfter.value.toUTCString())

        // get signature algorithm
     //   document.getElementById("sig-algo").innerHTML = algomap[cert_simpl.signatureAlgorithm.algorithm_id];
     //   document.getElementById("cert-data-block").style.display = "block";
        console.log(algomap[cert_simpl.signatureAlgorithm.algorithm_id])
    }
console.log(getCertificateData())
```

**Comment by carlskii** [comment]
I'll raise a new issue to cover it.

**Comment by happy2share** [comment]
I am getting the same issue. Is it resolved? Please point me the URL or give some sample code snippet to solve this.

**Comment by rmhrisk** [comment]
Yes, see https://github.com/PeculiarVentures/ASN1.js/issues/16 but I strongly recommend you work with https://github.com/PeculiarVentures/pkijs-es6 as it no longer requires merge and will be the basis of future improvements to the library.

**Comment by LiamDotPro** [comment]
Posting this as it's the most relevant issue when searching for parsing a PEM file in JS. The following code simply allows someone to pass the certificate string and provides back a simple object. This is in typescript but it would be trivial to modify it for pure ES6.

```
import Certificate from 'pkijs/src/Certificate'
import * as asn1js from 'asn1js'
import { decode } from 'base64-arraybuffer'
import Time from 'pkijs/src/Time'
import AttributeTypeAndValue from 'pkijs/src/AttributeTypeAndValue'
import * as moment from 'moment'

interface HumanCertificate {
    issuer: KeyInformation
    subject: KeyInformation
    validFrom: Time
    validTo: Time
    isValid: Boolean
    version: number
}

interface KeyInformation {
    distinguishedName: string
    components: {
        email: string
        commonName: string
        organizationalUnit: string
        organizationName: string
        localityName: string
        stateName: string
        country: string
    }
}

const formatDistinguishedName = (components: object) => {

    const nameMap = {
        country: 'C',
        organizationName: 'O',
        organizationalUnit: 'OU',
        commonName: 'CN',
        localityName: 'L',
        stateName: 'S',
        '2.5.4.12': 'T',
        '2.5.4.42': 'GN',
        '2.5.4.43': 'I',
        '2.5.4.4': 'SN',
        email: 'E-mail'
    }

    return Object.keys(components).filter(el => components[el])
        .map(key => `${nameMap[key]}=${components[key]}`)
        .join(',')
}

const validateToAndFrom = (from: Date, to: Date): Boolean => {
    if (!moment(from).isBefore(new Date())) {
        return false
    } else if (!moment(to).isAfter(new Date())) {
        return false
    }

    return true
}

const keyInformationFormatter = (outputObject: HumanCertificate, parentObj: string, typeValues: AttributeTypeAndValue[]): HumanCertificate => {

    const rdnmap = {
        '2.5.4.6': 'C',
        '2.5.4.10': 'O',
        '2.5.4.11': 'OU',
        '2.5.4.3': 'CN',
        '2.5.4.7': 'L',
        '2.5.4.8': 'S',
        '2.5.4.12': 'T',
        '2.5.4.42': 'GN',
        '2.5.4.43': 'I',
        '2.5.4.4': 'SN',
        '1.2.840.113549.1.9.1': 'E-mail'
    }

    // Issuer
    for (const typeAndValue of typeValues) {
        // @ts-ignore
        const typeval = rdnmap[typeAndValue.type]

        if (typeval === 'E-mail') {
            outputObject[parentObj].components.commonName = typeAndValue.value.valueBlock.value
        } else if (typeval === 'CN') {
            outputObject[parentObj].components.commonName = typeAndValue.value.valueBlock.value
        } else if (typeval === 'OU') {
            outputObject[parentObj].components.organizationalUnit = typeAndValue.value.valueBlock.value
        } else if (typeval === 'O') {
            outputObject[parentObj].components.organizationName = typeAndValue.value.valueBlock.value
        } else if (typeval === 'L') {
            outputObject[parentObj].components.localityName = typeAndValue.value.valueBlock.value
        } else if (typeval === 'ST') {
            outputObject[parentObj].components.stateName = typeAndValue.value.valueBlock.value
        } else if (typeval === 'C') {
            outputObject[parentObj].components.country = typeAndValue.value.valueBlock.value
        }
    }

    outputObject[parentObj].distinguishedName = formatDistinguishedName(outputObject[parentObj].components)

    return outputObject

}

const formatCertificateIntoHumanObjects = (certificate: Certificate): HumanCertificate => {

    let output: HumanCertificate = {
        issuer: {
            distinguishedName: '',
            components: {
                email: '',
                commonName: '',
                organizationalUnit: '',
                organizationName: '',
                localityName: '',
                stateName: '',
                country: ''
            }
        },
        subject: {
            distinguishedName: '',
            components: {
                email: '',
                commonName: '',
                organizationalUnit: '',
                organizationName: '',
                localityName: '',
                stateName: '',
                country: ''
            }
        },
        validFrom: certificate.notBefore,
        validTo: certificate.notAfter,
        isValid: validateToAndFrom(certificate.notBefore.value, certificate.notAfter.value),
        version: certificate.version
    }

    output = keyInformationFormatter(output, 'issuer', certificate.issuer.typesAndValues)
    output = keyInformationFormatter(output, 'subject', certificate.subject.typesAndValues)

    return output
}

const createCertificate = (certBuf: ArrayBuffer | undefined | ''): Certificate | undefined => {

    if (!certBuf) {
        return undefined
    }

    return new Certificate({ schema: asn1js.fromBER(certBuf).result })
}

export const parseCertificate = (cert: string): HumanCertificate[] | undefined => {

    const splitPEM = cert.split(`-----END CERTIFICATE-----`).map(el => {
        return el ? el.replace('-----BEGIN CERTIFICATE-----', '') : undefined
    }).filter(Boolean)

    const certBuf: (ArrayBuffer | undefined | '')[] = splitPEM.map(el => el && decode(el)).filter(Boolean)

    // @ts-ignore
    return certBuf.map(el => createCertificate(el)).filter(Boolean).map(el => formatCertificateIntoHumanObjects(el))

}
```

**Comment by weilah** [comment]
Hey @LiamDotPro you put that very nice together, thank you very much! I implemented your solution but I'm getting the same error as @carlskii did when passing an string with a PEM certificate: 

'ERROR Error: Object's schema was not verified against input data for Certificate'

I tried to follow the issue they opened but I can't crack it. Could you please me give me a hand it that matter?

By that time the solution seemed to be using something like : 
`var raw = new Buffer(CertPEM, 'base64').toString('binary')`;

but I think your solution already does this in this step: 
`const certBuf: (ArrayBuffer | undefined | '')[] = splitPEM.map(el => el && decode(el)).filter(Boolean);`

I'm not sure though. Anyway, thank you very much!

> Posting this as it's the most relevant issue when searching for parsing a PEM file in JS. The following code simply allows someone to pass the certificate string and provides back a simple object. This is in typescript but it would be trivial to modify it for pure ES6.
> 
> ```
> import Certificate from 'pkijs/src/Certificate'
> import * as asn1js from 'asn1js'
> import { decode } from 'base64-arraybuffer'
> import Time from 'pkijs/src/Time'
> import AttributeTypeAndValue from 'pkijs/src/AttributeTypeAndValue'
> import * as moment from 'moment'
> ```

**Comment by weilah** [comment]
Here is an example of a certificate that for me throws the error:

```
const testCert = `-----BEGIN CERTIFICATE-----
MIIDITCCAoqgAwIBAgIQT52W2WawmStUwpV8tBV9TTANBgkqhkiG9w0BAQUFADBM
MQswCQYDVQQGEwJaQTElMCMGA1UEChMcVGhhd3RlIENvbnN1bHRpbmcgKFB0eSkg
THRkLjEWMBQGA1UEAxMNVGhhd3RlIFNHQyBDQTAeFw0xMTEwMjYwMDAwMDBaFw0x
MzA5MzAyMzU5NTlaMGgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
MRYwFAYDVQQHFA1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKFApHb29nbGUgSW5jMRcw
FQYDVQQDFA53d3cuZ29vZ2xlLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkC
gYEA3rcmQ6aZhc04pxUJuc8PycNVjIjujI0oJyRLKl6g2Bb6YRhLz21ggNM1QDJy
wI8S2OVOj7my9tkVXlqGMaO6hqpryNlxjMzNJxMenUJdOPanrO/6YvMYgdQkRn8B
d3zGKokUmbuYOR2oGfs5AER9G5RqeC1prcB6LPrQ2iASmNMCAwEAAaOB5zCB5DAM
BgNVHRMBAf8EAjAAMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jcmwudGhhd3Rl
LmNvbS9UaGF3dGVTR0NDQS5jcmwwKAYDVR0lBCEwHwYIKwYBBQUHAwEGCCsGAQUF
BwMCBglghkgBhvhCBAEwcgYIKwYBBQUHAQEEZjBkMCIGCCsGAQUFBzABhhZodHRw
Oi8vb2NzcC50aGF3dGUuY29tMD4GCCsGAQUFBzAChjJodHRwOi8vd3d3LnRoYXd0
ZS5jb20vcmVwb3NpdG9yeS9UaGF3dGVfU0dDX0NBLmNydDANBgkqhkiG9w0BAQUF
AAOBgQAhrNWuyjSJWsKrUtKyNGadeqvu5nzVfsJcKLt0AMkQH0IT/GmKHiSgAgDp
ulvKGQSy068Bsn5fFNum21K5mvMSf3yinDtvmX3qUA12IxL/92ZzKbeVCq3Yi7Le
IOkKcGQRCMha8X2e7GmlpdWC1ycenlbN0nbVeSv3JUMcafC4+Q==
-----END CERTIFICATE-----`;
```

**Comment by YuryStrozhevsky** [comment]
@weilah All inputs for functions in PKI.js have `ArrayBuffer` type, not a Node.js's `Buffer`.

**Comment by weilah** [comment]
@YuryStrozhevsky thanks for the heads up. I'm actually using `ArrayBuffer` as I'm using @LiamDotPro 's approach. 

This is the code I'm running (not coping everything just the failing part)

```
const createCertificate = (certBuf: ArrayBuffer | undefined | ''): Certificate | undefined => {

    if (!certBuf) {
        return undefined
    }

    return new Certificate({ schema: asn1js.fromBER(certBuf).result })
}

export const parseCertificate = (): HumanCertificate[] | undefined => {

const cert: string = `-----BEGIN CERTIFICATE-----
MIIDITCCAoqgAwIBAgIQT52W2WawmStUwpV8tBV9TTANBgkqhkiG9w0BAQUFADBM
MQswCQYDVQQGEwJaQTElMCMGA1UEChMcVGhhd3RlIENvbnN1bHRpbmcgKFB0eSkg
THRkLjEWMBQGA1UEAxMNVGhhd3RlIFNHQyBDQTAeFw0xMTEwMjYwMDAwMDBaFw0x
MzA5MzAyMzU5NTlaMGgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
MRYwFAYDVQQHFA1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKFApHb29nbGUgSW5jMRcw
FQYDVQQDFA53d3cuZ29vZ2xlLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkC
gYEA3rcmQ6aZhc04pxUJuc8PycNVjIjujI0oJyRLKl6g2Bb6YRhLz21ggNM1QDJy
wI8S2OVOj7my9tkVXlqGMaO6hqpryNlxjMzNJxMenUJdOPanrO/6YvMYgdQkRn8B
d3zGKokUmbuYOR2oGfs5AER9G5RqeC1prcB6LPrQ2iASmNMCAwEAAaOB5zCB5DAM
BgNVHRMBAf8EAjAAMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jcmwudGhhd3Rl
LmNvbS9UaGF3dGVTR0NDQS5jcmwwKAYDVR0lBCEwHwYIKwYBBQUHAwEGCCsGAQUF
BwMCBglghkgBhvhCBAEwcgYIKwYBBQUHAQEEZjBkMCIGCCsGAQUFBzABhhZodHRw
Oi8vb2NzcC50aGF3dGUuY29tMD4GCCsGAQUFBzAChjJodHRwOi8vd3d3LnRoYXd0
ZS5jb20vcmVwb3NpdG9yeS9UaGF3dGVfU0dDX0NBLmNydDANBgkqhkiG9w0BAQUF
AAOBgQAhrNWuyjSJWsKrUtKyNGadeqvu5nzVfsJcKLt0AMkQH0IT/GmKHiSgAgDp
ulvKGQSy068Bsn5fFNum21K5mvMSf3yinDtvmX3qUA12IxL/92ZzKbeVCq3Yi7Le
IOkKcGQRCMha8X2e7GmlpdWC1ycenlbN0nbVeSv3JUMcafC4+Q==
-----END CERTIFICATE-----`;

    const splitPEM = cert.split(`-----END CERTIFICATE-----`).map(el => {
        return el ? el.replace('-----BEGIN CERTIFICATE-----', '') : undefined
    }).filter(Boolean)

    const certBuf: (ArrayBuffer | undefined | '')[] = splitPEM.map(el => el && decode(el)).filter(Boolean)

    // @ts-ignore
    return certBuf.map(el => createCertificate(el)).filter(Boolean).map(el => formatCertificateIntoHumanObjects(el))

}
```
and executing this line is where I get the error:

`new Certificate({ schema: asn1js.fromBER(certBuf).result })`

any thoughts? I appreciate your time

**Comment by weilah** [comment]
I've tracked down the error and `asn1js.fromBER(certBuf)` is returning me `error: "Too big integer"` inside the result object. I'll try to research on that an come back if I get the solution.

**Comment by YuryStrozhevsky** [comment]
@weilah I can easily parse your certificate using [**this live example**](https://pkijs.org/examples/X509_cert_complex_example.html), with no errors or exceptions.

So, again: please be 100% sure you have `ArrayBuffer` as an input for PKI.js functions. Also try to remove line endings in BASE-64 `const cert` string - sometimes BASE-64 decoding functions does not remove line endings and count it as an additional chars.

**Comment by weilah** [comment]
@YuryStrozhevsky You are for sure right and I'm probably doing something wrong in my end. I haven't found yet where the problem is. I'll take your advice and see if I get better results.

Just to be sure let me ask you: I installed PKIjs ("pkijs": "^2.1.78") and ASN1js ("asn1js": "^2.0.22") through npm in an Angluar8 (blank) project, this is totally fine with the library right?

Agin, thank you for your help

**Comment by YuryStrozhevsky** [comment]
@weilah Just install `latest` for these packages and all would be fine.

**Comment by weilah** [comment]
Oh my... lord. I'm very sorry. You were 100% the problem was some trailing spaces(?), chars(?) not sure what exactly because I tried to remove them by hand... anyway defining the certificate in just one line worked. Shame on me. Not doing so makes `asn1js.fromBER(certBuf)` fail.

Thanks @YuryStrozhevsky

**Comment by YuryStrozhevsky** [comment]
@weilah Glad to hear the news :)

**Comment by LiamDotPro** [comment]
Sorry for the late response, I actually ran into the same problem when I was writing out my solution in TS @weilah though in my case I've now extended the snippet above to keep a track of the original file with line endings as it requires the line endings in other packages that deal with pem file (noteably a java package).
